# Generated by Django 4.2 on 2024-11-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userSignup',
            new_name='signmodel',
        ),
    ]
